### ISSUE TITLE
checkpoint加载部分层参数的问题

### ISSUE THREAD

**Issue by spacingout** [zhenglab/technical-exchange#1]
师兄您好。我用Tensflow框架AlexNet网络训练一个训练集，得到了checkpoint，我想用这个checkpoint再来训练另一个训练集出现了形状不匹配问题，原因是：应该只加载checkpoint中前七层的数据，但是我加载了全部的数据。我查了半天也没搞懂怎么只加载前七层的数据,您有空帮我看下行吗，方便的话用teamviewer更好，谢谢。
[finetune_alexnet_with_tensorflow.tar.gz](https://github.com/zhenglab/technical-exchange/files/1426585/finetune_alexnet_with_tensorflow.tar.gz)

**Comment by spacingout** [comment]
自己把自己解决了..目前有两种方法可以解决这个问题，推荐第二种：
1、把数据从CKPT文件中提取出来，然后按照npy文件要求的格式存储，最后在接着套用程序代码读取即可，代码如下：
    `reader= pywrap_tensorflow.NewCheckpointReader(
            '/home/ouc/data/zsshi/checkpoints/model_epoch2.ckpt')
        var_to_shape_map = reader.get_variable_to_shape_map()
        listd = []
        for key in ``var_to_shape_map:`

            listd.append(key)
        dict = {}
        for i in listd:
            sdsd = reader.get_tensor(i)
            #pos = i.rfind("/")
            #b = i[:pos]
            dict[i] = sdsd
        weights_dict = {}
        weights_dict = {'conv1': [dict['conv1/weights'], dict['conv1/biases']],
                     'conv2': [dict['conv2/weights'], dict['conv2/biases']],
                     'conv3': [dict['conv3/weights'], dict['conv3/biases']],
                     'conv4': [dict['conv4/weights'], dict['conv4/biases']],
                     'conv5': [dict['conv5/weights'], dict['conv5/biases']],
                     'fc6': [dict['fc6/weights'], dict['fc6/biases']],
                     'fc7': [dict['fc7/weights'], dict['fc7/biases']],
                     'fc8': [dict['fc8/weights'], dict['fc8/biases']], }`
2、构建需要权重的层数的列表，利用tf.train.Saver()存储，之后在session里调用即可：
`saver1 = tf.train.Saver(var_lis)`
`with tf.Session() as sess:`
      `saver1.restore(sess, "checkpoint/model_test-1") `

**Comment by DAA233** [comment]
用 `tf.train.Saver()` 存储的 `ckpt` 文件，和你之前已有的 `ckpt` 文件有什么区别？之前的不可以用 `saver.restore` 读取吗？

**Comment by spacingout** [comment]
可以，只是这样可以对你想加载的参数（不是整个ckpt文件的参数）进行存储和加载而已 @DAA233

**Comment by DAA233** [comment]
嗯嗯，了解了。
